-- CreateTable
CREATE TABLE "Startup" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "logoUrl" TEXT,
    "shortDesc" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "status" BOOLEAN NOT NULL DEFAULT true,
    "publishState" TEXT NOT NULL DEFAULT 'DRAFT',
    "website" TEXT,
    "displayOrder" INTEGER NOT NULL DEFAULT 0,
    "tagline" TEXT,
    "description" TEXT NOT NULL,
    "techArea" TEXT,
    "businessModel" TEXT,
    "socialMedia" TEXT,
    "founderName" TEXT NOT NULL,
    "coFounders" TEXT,
    "designation" TEXT,
    "founderPhotoUrl" TEXT,
    "email" TEXT,
    "linkedIn" TEXT,
    "teamMembers" JSONB,
    "incubationDate" TIMESTAMP(3),
    "ecosystemStage" TEXT NOT NULL,
    "currentStage" TEXT NOT NULL,
    "registration" TEXT,
    "problemSolved" TEXT NOT NULL,
    "marketTarget" TEXT NOT NULL,
    "revenueModel" TEXT,
    "products" JSONB,
    "fundingStatus" TEXT,
    "fundingAmount" TEXT,
    "investors" TEXT,
    "investmentRound" TEXT,
    "govGrants" JSONB,
    "dpiitNumber" TEXT,
    "startupIndiaCert" TEXT,
    "isoCert" TEXT,
    "iprStatus" TEXT,
    "gstNumber" TEXT,
    "awards" TEXT,
    "press" TEXT,
    "keyMetrics" JSONB,
    "supportReceived" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Startup_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Startup_slug_key" ON "Startup"("slug");
